export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const SET_CATEGORIES_LIST = 'SET_CATEGORIES_LIST';
export const SET_FILTERS = 'SET_FILTERS';
