export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
