export const CREATE_CLIENT = 'CREATE_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_LIST = 'GET_CLIENT_LIST';
